version: '3'
 
# Define the services/ containers to be run
services:
    jira-sd:
        image: powpao/jira-sd:3.11.1
        container_name: jira-sd
        ports:
            - "8080:8080"
        command: 
            'bash -c "./opt/atlassian/jira/bin/start-jira.sh -fg"'
    jira-sd-db:
        image: mysql:5.7.21
        container_name: jira-sd-mysql
        volumes:
            - jira-sd-mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        command: mysqld --user=root --verbose --character-set-server=utf8 --collation-server=utf8_bin
        #environment:
        env_file:
            - ./mysql/jira-sd.env
    jira_confluence:
        image: powpao/jira-confluence:6.8.0
        container_name: jira-confluence
        ports:
            - "8090:8090"
        command: 
            'bash -c "./opt/atlassian/confluence/bin/start-confluence.sh -fg"'
    db_confluence:
        image: mysql:5.7.21
        container_name: jira-confluence-mysql
        volumes:
            - mysql-confluence:/var/lib/mysql
        ports:
            - "3307:3306"
        command: mysqld --user=root --verbose --character-set-server=utf8 --collation-server=utf8_bin --transaction-isolation=READ-COMMITTED
        env_file:
            - ./mysql/jira-confluence.env
volumes:
    jira-sd-mysql:
    mysql-confluence:
