version: '3'
 
# Define the services/ containers to be run
services:
    jira_confluence:
        image: powpao/jira-confluence:6.8.0
        container_name: jira-confluence
        ports:
            - "8090:8090"
        command: 
            'bash -c "./opt/atlassian/confluence/bin/start-confluence.sh -fg"'
    db_confluence:
        image: mysql:5.7.21
        container_name: jira-confluence-mysql
        volumes:
            - mysql-confluence:/var/lib/mysql
        ports:
            - "3307:3306"
        command: mysqld --user=root --verbose --character-set-server=utf8 --collation-server=utf8_bin --transaction-isolation=READ-COMMITTED
        env_file:
            - ./mysql/jira-confluence.env
volumes:
    mysql-confluence:
