version: '3'
 
# Define the services/ containers to be run
services:
    jira:
        image: powpao/jira-sd:3.11.1
        container_name: jira_helpdesk
        ports:
            - "8080:8080"
        command: 
            'bash -c "service jira start && tail -f /dev/null"'
    db:
        image: mysql:latest
        container_name: jira_mysql
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        command: mysqld --user=root --verbose --character-set-server=utf8 --collation-server=utf8_bin
        #environment:
        env_file:
            - ./mysql/.env
volumes:
    mysql:
